version: '3'
services:
  db:
    image: postgres:latest
    container_name: hotelier-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./psql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
